In [2]:
import tensorflow as tf

In [1]:
import numpy as np
from tensorflow import keras
from keras.layers import Input, Dense, Lambda, InputLayer, concatenate
from keras.models import Model, Sequential
from keras import backend as K
from keras import metrics
from keras.datasets import mnist
from keras.utils import np_utils

In [5]:
a = tf.constant([[1,1,1],[2,2,2]],dtype=tf.float32)
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [2., 2., 2.]], dtype=float32)>

In [6]:
b = 5 - a
b*a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [6., 6., 6.]], dtype=float32)>

In [7]:
tf.exp(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2.7182817, 2.7182817, 2.7182817],
       [7.389056 , 7.389056 , 7.389056 ]], dtype=float32)>

In [8]:
a**2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [4., 4., 4.]], dtype=float32)>

In [9]:
# trying
X = tf.constant([[1,0,1],[0,0,1]],shape=(2, 3),dtype=tf.float32)
X
X_mean = tf.constant([[0.1,0.5,0.8],[0.1,0.2,0.4]],shape=(2, 3),dtype=tf.float32)
tf.math.multiply(X,tf.math.log(X_mean))
tf.math.multiply(1-X,tf.math.log(X_mean))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.       , -0.6931472, -0.       ],
       [-2.3025851, -1.609438 , -0.       ]], dtype=float32)>

In [11]:
x = tf.constant([[1, 1, 1], [1, 1, 1]])
tf.reduce_sum(x)  # [2, 2, 2] ## [3, 3]


<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [13]:
import tensorflow.compat.v1 as tf

x = tf.placeholder(tf.float32)
y = tf.square(x)
z = tf.add(x, y)

sess = tf.Session()

z0 = sess.run([z], feed_dict={x: 2.})        # 6.0
z1 = sess.run([z], feed_dict={x: 2., y: 2.}) # 4.0

RuntimeError: tf.placeholder() is not compatible with eager execution.

In [16]:
import tensorflow as tf

@tf.function
def compute_z1(x, y):
  return tf.add(x, y)


def compute_z0(x):
       return compute_z1(x, tf.square(x))

z0 = compute_z0(2.)
z1 = compute_z1(2., 2.)

In [15]:
z0

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [3]:
def vlb_binomial(x, x_decoded_mean, t_mean, t_log_var):
    """Returns the value of negative Variational Lower Bound
    
    The inputs are tf.Tensor
        x: (batch_size x number_of_pixels) matrix with one image per row with zeros and ones
        x_decoded_mean: (batch_size x number_of_pixels) mean of the distribution p(x | t), real numbers from 0 to 1
        t_mean: (batch_size x latent_dim) mean vector of the (normal) distribution q(t | x)
        t_log_var: (batch_size x latent_dim) logarithm of the variance vector of the (normal) distribution q(t | x)
    
    Returns:
        A tf.Tensor with one element (averaged across the batch), VLB
    """
    ### YOUR CODE HERE
    # for part log(p(xi | hat(ti),w)) :
    # assume black is 1 and white is 0
    
    
    return tf.reduce_sum(x + x_decoded_mean) + tf.reduce_sum(t_mean+t_log_var)

# 尝试解决 Symbolic Tensor不兼容的问题 
# 尝试解决没有grandient生成的问题： loss函数必须是两个input，有其他的需要wrapper起来。 -- 
## 不需要使用 @tf.function 就行了...
理解： 下述代码原先是通过执行一个Sybolic tensor来凑成一个model。与那种定义一整个Model，每步都很清楚的那种，这个形式上比较自由打散。

In [4]:
test_data = np.load('test_data.npz')
loss = vlb_binomial(test_data['x'], test_data['x_decoded_mean'], test_data['t_mean'], test_data['t_log_var'])
loss

<tf.Tensor: shape=(), dtype=float32, numpy=18209.518>

In [5]:

batch_size = 100
original_dim = 784 # Number of pixels in MNIST images.
latent_dim = 3 # d, dimensionality of the latent code t.
intermediate_dim = 256 # Size of the hidden layer.
epochs = 2

x = Input(batch_shape=(batch_size, original_dim))

In [6]:
def create_encoder(input_dim):
    # Encoder network.
    # We instantiate these layers separately so as to reuse them later
    encoder = Sequential(name='encoder')
    encoder.add(InputLayer([input_dim]))
    encoder.add(Dense(intermediate_dim, activation='relu'))
    encoder.add(Dense(2 * latent_dim))
    return encoder

original_dim =784
intermediate_dim  = 2
latent_dim = 2
encoder = create_encoder(original_dim)

In [7]:
encoder

In [8]:
get_t_mean = Lambda(lambda h: h[:, :latent_dim])
get_t_log_var = Lambda(lambda h: h[:, latent_dim:])

h = encoder(x) # 这里使用了 numpy的数据？
t_mean = get_t_mean(h)
t_log_var = get_t_log_var(h)

In [9]:
t_log_var

<tf.Tensor 'lambda_1/strided_slice:0' shape=(100, 2) dtype=float32>

In [10]:
def sampling(args):
    t_mean, t_log_var = args
    # YOUR CODE HERE
    sample_std = tf.math.exp(t_log_var / 2.0)
    sample_shape = t_mean.shape
    sampled_normal = tf.random.normal(sample_shape)
    return t_mean + sample_std * sampled_normal


t = Lambda(sampling)([t_mean, t_log_var]) 
"""
这里对Lambda的使用方法类似前端JS的 IIFE (immediately Invoked Function Expression)
因此 这一步是evaluation
"""

def create_decoder(input_dim):
    # Decoder network
    # We instantiate these layers separately so as to reuse them later
    decoder = Sequential(name='decoder')
    decoder.add(InputLayer([input_dim]))
    decoder.add(Dense(intermediate_dim, activation='relu'))
    decoder.add(Dense(original_dim, activation='sigmoid'))
    return decoder
decoder = create_decoder(latent_dim)
x_decoded_mean = decoder(t)

In [11]:
t = Lambda(sampling)([t_mean, t_log_var]) 
t

<tf.Tensor 'lambda_3/add:0' shape=(100, 2) dtype=float32>

In [12]:
x_decoded_mean

<tf.Tensor 'decoder/dense_3/Sigmoid:0' shape=(100, 784) dtype=float32>

In [13]:
vae = Model(x, x_decoded_mean)

In [14]:
vae.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(100, 784)]         0                                            
__________________________________________________________________________________________________
encoder (Sequential)            (None, 4)            1582        input_1[0][0]                    
__________________________________________________________________________________________________
lambda (Lambda)                 (100, 2)             0           encoder[0][0]                    
__________________________________________________________________________________________________
lambda_1 (Lambda)               (100, 2)             0           encoder[0][0]                    
_______________________________________________________________________________________

In [15]:
# keras.utils.plot_model(vae, "my_first_model.png")

In [27]:
loss = vlb_binomial(x, x_decoded_mean, t_mean, t_log_var)
def wrapper_loss(x, x_decoded_mean):
    print("hit")
    return vlb_binomial(x, x_decoded_mean, t_mean, t_log_var)

In [28]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

x_train = x_train.reshape(60000, 784).astype("float32") / 255
x_test = x_test.reshape(10000, 784).astype("float32") / 255

# vae.compile(optimizer=keras.optimizers.RMSprop(lr=0.001), loss=lambda x, y: loss)
vae.compile(optimizer=keras.optimizers.RMSprop(lr=0.001),loss= wrapper_loss)


In [29]:
vae.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(100, 784)]         0                                            
__________________________________________________________________________________________________
encoder (Sequential)            (None, 4)            1582        input_1[0][0]                    
__________________________________________________________________________________________________
lambda (Lambda)                 (100, 2)             0           encoder[0][0]                    
__________________________________________________________________________________________________
lambda_1 (Lambda)               (100, 2)             0           encoder[0][0]                    
_______________________________________________________________________________________

In [30]:

hist = vae.fit(x=x_train, y=x_train,
               shuffle=True,
               epochs=epochs,
               batch_size=batch_size,
               validation_data=(x_test, x_test),
               verbose=2)

Epoch 1/2
hit
hit


_SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'lambda/strided_slice:0' shape=(100, 2) dtype=float32>, <tf.Tensor 'lambda_1/strided_slice:0' shape=(100, 2) dtype=float32>]

In [62]:
test_scores = vae.evaluate(x_test, y_test, verbose=2)
print("Test loss:", test_scores[0])
print("Test accuracy:", test_scores[1])

Epoch 1/2
479/480 [============================>.] - ETA: 0s - loss: 5.9368 - accuracy: 0.1139

InvalidArgumentError:  Incompatible shapes: [64,1] vs. [100,3]
	 [[node functional_2/lambda_18/mul (defined at <ipython-input-54-874927fd1ecf>:18) ]] [Op:__inference_test_function_4992]

Errors may have originated from an input operation.
Input Source operations connected to node functional_2/lambda_18/mul:
 functional_2/lambda_18/Exp (defined at <ipython-input-54-874927fd1ecf>:15)	
 functional_2/lambda_18/random_normal (defined at <ipython-input-54-874927fd1ecf>:17)

Function call stack:
test_function
